package com.halal.sa.common.error;

public class DomainErrorConstants {
	
	private DomainErrorConstants() {
		// Added as part of sonar fix
	}
	public static final String ERR_V1_BING_IO = "ERR_V1_BING_IO";
	public static final String ERR_LOCATION_V1_BING_DE_SERIALIZING_FROM_JSON = 
			"ERR_LOCATION_V1_BING_DE_SERIALIZING_FROM_JSON";
	public static final String ERR_LOCATION_V1_BING_BAD_REQUEST = 
			"ERR_LOCATION_V1_BING_BAD_REQUEST";
	
	public static final String ERR_STORE_SEARCH_V1_BING_DE_SERIALIZING_FROM_JSON = 
			"ERR_STORE_SEARCH_V1_BING_DE_SERIALIZING_FROM_JSON";
	
	public static final String ERR_ROUTE_V1_BING_RECORD_NOT_FOUND = 
			"ERR_ROUTE_V1_BING_RECORD_NOT_FOUND";
	public static final String ERR_ROUTE_V1_BING_BAD_REQUEST = 
			"ERR_ROUTE_V1_BING_BAD_REQUEST";
	public static final String ERR_ROUTE_V1_BING_INTERNAL_SERVER = 
			"ERR_ROUTE_V1_BING_INTERNAL_SERVER";
	public static final String ERR_ROUTE_V1_BING_SERVICE_UNAVAILABLE = 
			"ERR_ROUTE_V1_BING_SERVICE_UNAVAILABLE";
	public static final String ERR_ROUTE_V1_BING_UNAUTHORIZED = 
			"ERR_ROUTE_V1_BING_UNAUTHORIZED";
	public static final String ERR_ROUTE_V1_BING_HTTP_RESPONSE_CODE = 
			"ERR_ROUTE_V1_BING_HTTP_RESPONSE_CODE";
	public static final String ERR_ROUTE_V1_BING_CONNECTION_POOL_TIMEOUT = 
			"ERR_ROUTE_V1_BING_CONNECTION_POOL_TIMEOUT";
	public static final String ERR_ROUTE_V1_BING_CONNECT_TIMEOUT = 
			"ERR_ROUTE_V1_BING_CONNECT_TIMEOUT";
	public static final String ERR_ROUTE_V1_BING_SOCKET_TIMEOUT = 
			"ERR_ROUTE_V1_BING_SOCKET_TIMEOUT";
	public static final String ERR_ROUTE_V1_BING_HTTP_HOST_CONNECT = 
			"ERR_ROUTE_V1_BING_HTTP_HOST_CONNECT";
	public static final String ERR_ROUTE_V1_BING_CLIENT_PROTOCOL = 
			"ERR_ROUTE_V1_BING_CLIENT_PROTOCOL";
	public static final String ERR_ROUTE_V1_BING_IO = "ERR_ROUTE_V1_BING_IO";
	public static final String ERR_ROUTE_V1_BING_DE_SERIALIZING_FROM_JSON = 
			"ERR_ROUTE_V1_BING_DE_SERIALIZING_FROM_JSON";
	
	public static final String ERR_SPATIALQUERY_V1_BING_ADDRESS_RECORD_NOT_FOUND = 
			"ERR_SPATIALQUERY_V1_BING_ADDRESS_RECORD_NOT_FOUND";
	public static final String ERR_SPATIALQUERY_V1_BING_RECORD_NOT_FOUND = 
			"ERR_SPATIALQUERY_V1_BING_RECORD_NOT_FOUND";
	public static final String ERR_SPATIALQUERY_V1_BING_BAD_REQUEST = 
			"ERR_SPATIALQUERY_V1_BING_BAD_REQUEST";
	public static final String ERR_SPATIALQUERY_V1_BING_INTERNAL_SERVER = 
			"ERR_SPATIALQUERY_V1_BING_INTERNAL_SERVER";
	public static final String ERR_SPATIALQUERY_V1_BING_SERVICE_UNAVAILABLE = 
			"ERR_SPATIALQUERY_V1_BING_SERVICE_UNAVAILABLE";
	public static final String ERR_SPATIALQUERY_V1_BING_UNAUTHORIZED = 
			"ERR_SPATIALQUERY_V1_BING_UNAUTHORIZED";
	public static final String ERR_SPATIALQUERY_V1_BING_HTTP_RESPONSE_CODE = 
			"ERR_SPATIALQUERY_V1_BING_HTTP_RESPONSE_CODE";
	public static final String ERR_SPATIALQUERY_V1_BING_CONNECTION_POOL_TIMEOUT = 
			"ERR_SPATIALQUERY_V1_BING_CONNECTION_POOL_TIMEOUT";
	public static final String ERR_SPATIALQUERY_V1_BING_CONNECT_TIMEOUT = 
			"ERR_SPATIALQUERY_V1_BING_CONNECT_TIMEOUT";
	public static final String ERR_SPATIALQUERY_V1_BING_SOCKET_TIMEOUT = 
			"ERR_SPATIALQUERY_V1_BING_SOCKET_TIMEOUT";
	public static final String ERR_SPATIALQUERY_V1_BING_HTTP_HOST_CONNECT = 
			"ERR_SPATIALQUERY_V1_BING_HTTP_HOST_CONNECT";
	public static final String ERR_SPATIALQUERY_V1_BING_CLIENT_PROTOCOL = 
			"ERR_SPATIALQUERY_V1_BING_CLIENT_PROTOCOL";
	public static final String ERR_SPATIALQUERY_V1_BING_IO = "ERR_SPATIALQUERY_V1_BING_IO";
	public static final String ERR_SPATIALQUERY_V1_BING_DE_SERIALIZING_FROM_JSON = 
			"ERR_SPATIALQUERY_V1_BING_DE_SERIALIZING_FROM_JSON";
	
	public static final String ERR_V2_STORESEARCH_AMBIGUOUS_ADDRESS = 
	        "ERR_V2_STORESEARCH_AMBIGUOUS_ADDRESS";
	
	public static final String ERR_STORE_SEARCH_SERVICE_V2_BAD_REQUEST = "ERR_STORE_SEARCH_SERVICE_V2_BAD_REQUEST";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_UNAUTHORIZED = "ERR_STORE_SEARCH_SERVICE_V2_UNAUTHORIZED";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_RECORD_NOT_FOUND = "ERR_STORE_SEARCH_SERVICE_V2_RECORD_NOT_FOUND";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_INTERNAL_SERVER = "ERR_STORE_SEARCH_SERVICE_V2_INTERNAL_SERVER";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_SERVICE_UNAVAILABLE = "ERR_STORE_SEARCH_SERVICE_V2_SERVICE_UNAVAILABLE";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_HTTP_RESPONSE_CODE = "ERR_STORE_SEARCH_SERVICE_V2_HTTP_RESPONSE_CODE";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_CONNECTION_POOL_TIMEOUT = "ERR_STORE_SEARCH_SERVICE_V2_CONNECTION_POOL_TIMEOUT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_CONNECT_TIMEOUT = "ERR_STORE_SEARCH_SERVICE_V2_CONNECT_TIMEOUT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_HTTP_HOST_CONNECT = "ERR_STORE_SEARCH_SERVICE_V2_HTTP_HOST_CONNECT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_SOCKET_TIMEOUT = "ERR_STORE_SEARCH_SERVICE_V2_SOCKET_TIMEOUT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_CLIENT_PROTOCOL = "ERR_STORE_SEARCH_SERVICE_V2_CLIENT_PROTOCOL";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_IO = "ERR_STORE_SEARCH_SERVICE_V2_IO";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_DE_SERIALIZING_FROM_JSON = "ERR_STORE_SEARCH_SERVICE_V2_DE_SERIALIZING_FROM_JSON";
	
	public static final String ERR_INVALID_REQUEST_PARAMETERS = "ERR_INVALID_REQUEST_PARAMETERS";

	
	
}