package com.halal.sa.core.exception;

public class DomainErrorConstants {
	
	private DomainErrorConstants() {
		// Added as part of sonar fix
	}
	
	
	public static final String ERRCODE_INCOMPLETE_DATA = "ERR_INCOMPLETE_DATA";	
	public static final String ERRCODE_BAD_REQUEST = "ERR_BAD_REQUEST";
	public static final String ERR_SEARCH_RECORD_NOT_FOUND = "SEARCH_RECORD_NOT_FOUND";
	
	public static final String ERRDESC_TOKEN_MISSING = "Session or Activity token is required in request param";	
	
	public static final String ERR_STORE_SEARCH_SERVICE_V2_UNAUTHORIZED = "ERR_STORE_SEARCH_SERVICE_V2_UNAUTHORIZED";
	
	public static final String ERR_STORE_SEARCH_SERVICE_V2_INTERNAL_SERVER = "ERR_STORE_SEARCH_SERVICE_V2_INTERNAL_SERVER";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_SERVICE_UNAVAILABLE = "ERR_STORE_SEARCH_SERVICE_V2_SERVICE_UNAVAILABLE";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_HTTP_RESPONSE_CODE = "ERR_STORE_SEARCH_SERVICE_V2_HTTP_RESPONSE_CODE";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_CONNECTION_POOL_TIMEOUT = "ERR_STORE_SEARCH_SERVICE_V2_CONNECTION_POOL_TIMEOUT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_CONNECT_TIMEOUT = "ERR_STORE_SEARCH_SERVICE_V2_CONNECT_TIMEOUT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_HTTP_HOST_CONNECT = "ERR_STORE_SEARCH_SERVICE_V2_HTTP_HOST_CONNECT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_SOCKET_TIMEOUT = "ERR_STORE_SEARCH_SERVICE_V2_SOCKET_TIMEOUT";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_CLIENT_PROTOCOL = "ERR_STORE_SEARCH_SERVICE_V2_CLIENT_PROTOCOL";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_IO = "ERR_STORE_SEARCH_SERVICE_V2_IO";
	public static final String ERR_STORE_SEARCH_SERVICE_V2_DE_SERIALIZING_FROM_JSON = "ERR_STORE_SEARCH_SERVICE_V2_DE_SERIALIZING_FROM_JSON";
	
	public static final String ERR_INVALID_REQUEST_PARAMETERS = "ERR_INVALID_REQUEST_PARAMETERS";

	public static final String ERR_GOOGLE_API_HTTP_HOST_CONNECT =  "ERR_GOOGLE_API_HTTP_HOST_CONNECT";
	public static final String ERR_GOOGLE_API_HTTP_EXCEPTION =  "ERR_GOOGLE_API_HTTP_EXCEPTION";
	
}